version: '3.8'

services:
  citymaster-webapp:
    container_name: citymaster-webapp
    image: node:20-alpine
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PGUSER=postgres
      - PGPASSWORD=Tsuki4545!
      - PGHOST=citymaster-db
      - PGPORT=5432
      - PGDATABASE=citymaster
      - JWT_SECRET=ChangeThisSecretKeyToSomethingVerySecure!
    ports:
      - "3000:3000"
    volumes:
      - /home/familytsuki/CityMaster:/app
    working_dir: /app
    command: npm run start
    restart: unless-stopped
    depends_on:
      - citymaster-db
    networks:
      - citymaster-network

  citymaster-db:
    container_name: citymaster-db
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Tsuki4545!
      - POSTGRES_DB=citymaster
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - citymaster-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - citymaster-network

  cloudflared-tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token VOTRE_TOKEN_CLOUDFLARE_ICI
    network_mode: "host"

volumes:
  citymaster-db-data:

networks:
  citymaster-network:
    name: cosmos-citymaster-default
